#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")"

ENV_FILE=".env"
DEFAULT_PREFIX="wingman"
DEFAULT_IMAGE="wingman-autopilot:local"
DEFAULT_CONTAINER_PORT="3600"
DEFAULT_AGENT_PORTS="3700"
DEFAULT_AGENT_MAX="10"

fail() {
  printf 'Error: %s\n' "$1" >&2
  exit 1
}

have() {
  command -v "$1" >/dev/null 2>&1
}

compose() {
  docker compose "$@"
}

prompt() {
  local label="$1"
  local default_value="${2:-}"
  local value
  if [[ -n "$default_value" ]]; then
    read -r -p "$label [$default_value]: " value
    printf '%s' "${value:-$default_value}"
  else
    read -r -p "$label: " value
    printf '%s' "$value"
  fi
}

prompt_secret() {
  local label="$1"
  local value
  read -r -s -p "$label: " value
  printf '\n' >&2
  printf '%s' "$value"
}

confirm() {
  local label="$1"
  local default_value="${2:-y}"
  local answer
  read -r -p "$label [$default_value]: " answer
  answer="${answer:-$default_value}"
  [[ "$answer" == "y" || "$answer" == "Y" || "$answer" == "yes" || "$answer" == "YES" ]]
}

quote_env_value() {
  local value="$1"
  if [[ "$value" =~ ^[A-Za-z0-9_./:@,+-]*$ ]]; then
    printf '%s' "$value"
  else
    printf '"%s"' "${value//\"/\\\"}"
  fi
}

generate_secret() {
  if have openssl; then
    openssl rand -base64 48 | tr '+/' '-_' | tr -d '=\n'
    return
  fi
  if have python3; then
    python3 - <<'PY'
import base64, os
print(base64.urlsafe_b64encode(os.urandom(48)).decode().rstrip("="))
PY
    return
  fi
  fail "openssl or python3 is required to generate IDENTITY_SESSION_SECRET"
}

compose_project_exists() {
  local name="$1"
  local projects
  projects="$(compose ls --format json 2>/dev/null || true)"
  [[ "$projects" == *"\"Name\":\"$name\""* || "$projects" == *"\"Name\": \"$name\""* ]]
}

pick_instance() {
  local index candidate
  for index in $(seq 1 999); do
    candidate="${DEFAULT_PREFIX}-$(printf '%02d' "$index")"
    if ! compose_project_exists "$candidate"; then
      printf '%s:%s' "$candidate" "$index"
      return
    fi
  done
  fail "could not find an available wingman-## Compose project name"
}

expand_path() {
  local value="$1"
  if [[ "$value" == "~" ]]; then
    printf '%s' "$HOME"
  elif [[ "$value" == "~/"* ]]; then
    printf '%s/%s' "$HOME" "${value#~/}"
  else
    printf '%s' "$value"
  fi
}

write_env() {
  local index key value
  : >"$ENV_FILE"
  chmod 600 "$ENV_FILE"
  {
    printf '# Generated by setupwizard.sh\n'
    printf '# Run docker compose exec wingman bash for agent CLI login.\n\n'
    for index in "${!ENV_KEYS[@]}"; do
      key="${ENV_KEYS[$index]}"
      value="${ENV_VALUES[$index]}"
      printf '%s=%s\n' "$key" "$(quote_env_value "$value")"
    done
  } >>"$ENV_FILE"
}

ENV_KEYS=()
ENV_VALUES=()

add_env() {
  ENV_KEYS+=("$1")
  ENV_VALUES+=("$2")
}

require_valid_npub() {
  local value="$1"
  [[ "$value" == npub1* && "${#value}" -ge 20 ]] || fail "admin npub must start with npub1"
}

have docker || fail "docker is required"
compose version >/dev/null 2>&1 || fail "docker compose is required"

printf '\nWingman Autopilot Docker Setup\n'
printf 'This writes %s, creates the host workspace directory, then builds and starts Docker.\n\n' "$ENV_FILE"

if [[ -f "$ENV_FILE" ]]; then
  confirm "$ENV_FILE already exists. Overwrite it?" "n" || fail "setup cancelled"
fi

picked="$(pick_instance)"
default_instance="${picked%%:*}"
default_index="${picked##*:}"
default_host_port="$((DEFAULT_CONTAINER_PORT + default_index - 1))"
default_workspace="$HOME/.wm-ap"
if [[ "$default_index" != "1" ]]; then
  default_workspace="$HOME/.wm-ap$(printf '%02d' "$default_index")"
fi

admin_npub="$(prompt "Admin npub")"
require_valid_npub "$admin_npub"

instance_name="$(prompt "Instance name" "$default_instance")"
host_port="$(prompt "Host port" "$default_host_port")"
[[ "$host_port" =~ ^[0-9]+$ && "$host_port" -ge 1 && "$host_port" -le 65535 ]] || fail "host port must be 1-65535"

base_url="$(prompt "Public base URL" "http://localhost:$host_port")"
workspace_host_path="$(expand_path "$(prompt "Host workspace path mounted at /workspace" "$default_workspace")")"

routing_mode="$(prompt "Hosted app routing mode: path or subdomain" "path")"
case "$routing_mode" in
  path)
    subdomain_base_domain=""
    ;;
  subdomain)
    subdomain_base_domain="$(prompt "Subdomain base domain, e.g. wmd.example.com")"
    [[ -n "$subdomain_base_domain" ]] || fail "subdomain base domain is required for subdomain routing"
    ;;
  *)
    fail "routing mode must be path or subdomain"
    ;;
esac

wingman_priv=""
if confirm "Set WINGMAN_PRIV now? Leave this as no if you want to add it later" "n"; then
  wingman_priv="$(prompt_secret "WINGMAN_PRIV nsec")"
fi

cookie_secure="false"
if [[ "$base_url" == https://* ]]; then
  cookie_secure="true"
fi

mkdir -p "$workspace_host_path"

add_env "COMPOSE_PROJECT_NAME" "$instance_name"
add_env "WINGMAN_INSTANCE_NAME" "$instance_name"
add_env "WINGMAN_IMAGE" "$DEFAULT_IMAGE"
add_env "WINGMAN_HOST_PORT" "$host_port"
add_env "WINGMAN_CONTAINER_PORT" "$DEFAULT_CONTAINER_PORT"
add_env "WINGMAN_AGENT_PORTS" "$DEFAULT_AGENT_PORTS"
add_env "WINGMAN_AGENT_MAX" "$DEFAULT_AGENT_MAX"
add_env "WINGMAN_DIRECTORY_DEF" "/workspace"
add_env "WINGMAN_FOLDERACCESS" "/workspace"
add_env "WINGMAN_WORKSPACE_HOST_PATH" "$workspace_host_path"
add_env "WINGMAN_BASE_URL" "$base_url"
add_env "WINGMAN_IDENTITY_COOKIE_SECURE" "$cookie_secure"
add_env "WINGMAN_APP_ROUTING" "$routing_mode"
add_env "WINGMAN_SUBDOMAIN_BASE_DOMAIN" "$subdomain_base_domain"
add_env "WINGMAN_SUBDOMAIN_PROXY_ENABLED" "true"
add_env "WINGMAN_AGENT_SPAWN_MODE" "bun"
add_env "WINGMAN_AGENTAPI_ALLOWED_HOSTS" "localhost,127.0.0.1,[::1]"
add_env "WINGMAN_CODEX_CLI" "/usr/local/bin/codex"
add_env "WINGMAN_CODEX_TRUSTED_WORKSPACE" "/workspace"
add_env "WINGMAN_CLAUDE_CLI" "/usr/local/bin/claude"
add_env "WINGMAN_GOOSE_CLI" "/usr/local/bin/goose"
add_env "WINGMAN_OPENCODE_CLI" "/usr/local/bin/opencode"
add_env "WINGMAN_GEMINI_CLI" "/usr/local/bin/gemini"
add_env "WINGMAN_PI_CLI" "/usr/local/bin/pi"
add_env "WINGMAN_IDENTITY_SESSION_SECRET" "$(generate_secret)"
add_env "WINGMAN_ADMIN_NPUB" "$admin_npub"
add_env "WINGMAN_PRIV" "$wingman_priv"
add_env "WINGMAN_REGISTER" "false"
add_env "WINGMAN_SETUP_NONINTERACTIVE" "true"

write_env

printf '\nWrote %s\n' "$ENV_FILE"
printf 'Workspace: %s -> /workspace\n' "$workspace_host_path"
printf 'URL: %s\n\n' "$base_url"

if confirm "Build and start Docker now?" "y"; then
  compose up -d --build
  printf '\nDocker started. Check status with:\n'
  printf '  docker compose ps\n'
  printf '  docker compose logs --tail=100 wingman\n\n'
  printf 'To log into agent CLIs inside the container:\n'
  printf '  docker compose exec wingman bash\n'
else
  printf 'Skipped Docker start. Run this when ready:\n'
  printf '  docker compose up -d --build\n'
fi
