/**
 * Ecosystem config file generator for PM2.
 * Each user gets their own ecosystem.config.cjs in their root folder.
 * Admin uses ./data/admin/ecosystem.config.cjs
 */

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";

import type { AgentType, WingmanConfig } from "../config";
import type { AppRecord } from "../apps/app-registry";

export interface EcosystemApp {
  name: string;
  script: string;
  args: string[];
  cwd: string;
  env: Record<string, string>;
  out_file: string;
  error_file: string;
  log_date_format: string;
  merge_logs: boolean;
  autorestart: boolean;
  max_restarts: number;
  min_uptime: string;
}

export interface EcosystemConfig {
  apps: EcosystemApp[];
}

export interface SessionConfig {
  sessionId: string;
  sessionName: string;
  agent: AgentType;
  port: number;
  workingDirectory: string;
  userAlias: string;
  isAdmin: boolean;
  config: WingmanConfig;
}

const ECOSYSTEM_FILENAME = "ecosystem.config.cjs";
const ADMIN_DATA_DIR = "./data/admin";

/**
 * Get the ecosystem config file path for a user.
 * Admin: ./data/admin/ecosystem.config.cjs
 * Regular users: ~/code/<alias>/ecosystem.config.cjs
 */
export function getEcosystemPath(userRootDir: string, isAdmin: boolean): string {
  if (isAdmin) {
    return join(ADMIN_DATA_DIR, ECOSYSTEM_FILENAME);
  }
  return join(userRootDir, ECOSYSTEM_FILENAME);
}

/**
 * Get the logs directory for a user.
 * Admin: ./data/admin/apps/logs/
 * Regular users: ~/code/<alias>/apps/logs/
 */
export function getLogsDirectory(userRootDir: string, isAdmin: boolean): string {
  if (isAdmin) {
    return join(ADMIN_DATA_DIR, "apps", "logs");
  }
  return join(userRootDir, "apps", "logs");
}

/**
 * Generate a PM2 process name from user alias and session name.
 * Format: {alias}-{sanitized-session-name}
 */
export function generateProcessName(userAlias: string, sessionName: string): string {
  const sanitizedAlias = userAlias.toLowerCase().replace(/[^a-z0-9-]/g, "");
  const sanitizedName = sessionName.toLowerCase().replace(/[^a-z0-9-]/g, "-").replace(/-+/g, "-").replace(/^-|-$/g, "");
  const truncatedName = sanitizedName.slice(0, 32) || "session";
  return `${sanitizedAlias}-${truncatedName}`;
}

/**
 * Read an existing ecosystem config file.
 * Returns empty config if file doesn't exist.
 */
export async function readEcosystemConfig(ecosystemPath: string): Promise<EcosystemConfig> {
  try {
    const content = await readFile(ecosystemPath, "utf-8");
    // Parse the CommonJS module format
    // The file format is: module.exports = { apps: [...] }
    const match = content.match(/module\.exports\s*=\s*(\{[\s\S]*\})\s*;?\s*$/);
    if (!match) {
      return { apps: [] };
    }
    // Use Function constructor to safely evaluate the object literal
    // This avoids eval() while still parsing the JS object
    const configStr = match[1];
    const parseConfig = new Function(`return ${configStr}`);
    const config = parseConfig() as EcosystemConfig;
    return config;
  } catch (error) {
    const nodeError = error as NodeJS.ErrnoException;
    if (nodeError.code === "ENOENT") {
      return { apps: [] };
    }
    throw error;
  }
}

/**
 * Write an ecosystem config file.
 * Creates parent directories if they don't exist.
 */
export async function writeEcosystemConfig(
  ecosystemPath: string,
  config: EcosystemConfig,
): Promise<void> {
  await mkdir(dirname(ecosystemPath), { recursive: true });

  const content = `// PM2 Ecosystem Configuration
// Auto-generated by Wingman - do not edit manually
module.exports = ${JSON.stringify(config, null, 2)};
`;

  await writeFile(ecosystemPath, content, "utf-8");
}

/**
 * Build the agentapi command for a session.
 */
function buildAgentCommand(sessionConfig: SessionConfig): { script: string; args: string[] } {
  const { agent, port, config } = sessionConfig;
  const definition = config.agents[agent];
  const commandParts = definition.command({ port, agent, config });

  if (commandParts.length === 0) {
    throw new Error(`Agent ${agent} command returned empty array`);
  }

  // First element is the script (agentapi binary), rest are args
  const [script, ...args] = commandParts;
  return { script: script!, args };
}

/**
 * Create an ecosystem app entry for a session.
 */
export function createAppConfig(sessionConfig: SessionConfig): EcosystemApp {
  const { sessionId, sessionName, port, workingDirectory, userAlias, isAdmin } = sessionConfig;
  const processName = generateProcessName(userAlias, sessionName);
  const logsDir = getLogsDirectory(workingDirectory, isAdmin);
  const { script, args } = buildAgentCommand(sessionConfig);

  return {
    name: processName,
    script,
    args,
    cwd: workingDirectory,
    env: {
      SESSION_ID: sessionId,
      SESSION_NAME: sessionName,
      SESSION_PORT: String(port),
      SESSION_DIRECTORY: workingDirectory,
      SESSION_AGENT: sessionConfig.agent,
      USER_ALIAS: userAlias,
    },
    out_file: join(logsDir, `${processName}-out.log`),
    error_file: join(logsDir, `${processName}-error.log`),
    log_date_format: "YYYY-MM-DD HH:mm:ss",
    merge_logs: true,
    autorestart: false,
    max_restarts: 0,
    min_uptime: "5s",
  };
}

/**
 * Add an app to a user's ecosystem config.
 * Creates the file if it doesn't exist.
 */
export async function addAppToEcosystem(
  sessionConfig: SessionConfig,
): Promise<{ ecosystemPath: string; processName: string; logsDir: string }> {
  const ecosystemPath = getEcosystemPath(sessionConfig.workingDirectory, sessionConfig.isAdmin);
  const logsDir = getLogsDirectory(sessionConfig.workingDirectory, sessionConfig.isAdmin);

  // Ensure logs directory exists
  await mkdir(logsDir, { recursive: true });

  // Read existing config
  const config = await readEcosystemConfig(ecosystemPath);

  // Create app config
  const appConfig = createAppConfig(sessionConfig);

  // Check if app with same name already exists
  const existingIndex = config.apps.findIndex((app) => app.name === appConfig.name);
  if (existingIndex >= 0) {
    // Update existing entry
    config.apps[existingIndex] = appConfig;
  } else {
    // Add new entry
    config.apps.push(appConfig);
  }

  // Write updated config
  await writeEcosystemConfig(ecosystemPath, config);

  return {
    ecosystemPath,
    processName: appConfig.name,
    logsDir,
  };
}

/**
 * Remove an app from a user's ecosystem config by process name.
 */
export async function removeAppFromEcosystem(
  userRootDir: string,
  isAdmin: boolean,
  processName: string,
): Promise<boolean> {
  const ecosystemPath = getEcosystemPath(userRootDir, isAdmin);

  try {
    const config = await readEcosystemConfig(ecosystemPath);
    const initialLength = config.apps.length;
    config.apps = config.apps.filter((app) => app.name !== processName);

    if (config.apps.length === initialLength) {
      // App wasn't in config
      return false;
    }

    await writeEcosystemConfig(ecosystemPath, config);
    return true;
  } catch (error) {
    const nodeError = error as NodeJS.ErrnoException;
    if (nodeError.code === "ENOENT") {
      return false;
    }
    throw error;
  }
}

/**
 * Find an app in the ecosystem config by session ID.
 * Searches through env vars since SESSION_ID is stored there.
 */
export async function findAppBySessionId(
  userRootDir: string,
  isAdmin: boolean,
  sessionId: string,
): Promise<EcosystemApp | null> {
  const ecosystemPath = getEcosystemPath(userRootDir, isAdmin);

  try {
    const config = await readEcosystemConfig(ecosystemPath);
    return config.apps.find((app) => app.env.SESSION_ID === sessionId) ?? null;
  } catch {
    return null;
  }
}

/**
 * List all apps in a user's ecosystem config.
 */
export async function listAppsInEcosystem(
  userRootDir: string,
  isAdmin: boolean,
): Promise<EcosystemApp[]> {
  const ecosystemPath = getEcosystemPath(userRootDir, isAdmin);

  try {
    const config = await readEcosystemConfig(ecosystemPath);
    return config.apps;
  } catch {
    return [];
  }
}

// =============================================================================
// User App (non-agent) PM2 Configuration
// =============================================================================

export interface UserAppConfig {
  app: AppRecord;
  userAlias: string;
  userRootDir: string;
  isAdmin: boolean;
}

/**
 * Generate a PM2 process name for a user app.
 * Format: {alias}-app-{sanitized-label}
 * The "-app-" infix distinguishes apps from agent sessions.
 */
export function generateAppProcessName(userAlias: string, appLabel: string): string {
  const sanitizedAlias = userAlias.toLowerCase().replace(/[^a-z0-9-]/g, "");
  const sanitizedLabel = appLabel
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
  const truncatedLabel = sanitizedLabel.slice(0, 32) || "app";
  return `${sanitizedAlias}-app-${truncatedLabel}`.slice(0, 48);
}

/**
 * Create an ecosystem app entry for a user app.
 */
export function createUserAppEcosystemConfig(config: UserAppConfig): EcosystemApp {
  const { app, userAlias, userRootDir, isAdmin } = config;
  const processName = generateAppProcessName(userAlias, app.label);
  const logsDir = getLogsDirectory(userRootDir, isAdmin);

  // Get the start script
  const startScript = app.scripts.start;
  if (!startScript) {
    throw new Error(`App ${app.id} has no start script defined`);
  }

  // Build command with port override for web apps
  let command = startScript;
  if (app.webApp && app.webAppPort) {
    command = `PORT=${app.webAppPort} ${startScript}`;
  }

  return {
    name: processName,
    script: "bash",
    args: ["-c", command],
    cwd: app.root,
    env: {
      APP_ID: app.id,
      APP_LABEL: app.label,
      USER_ALIAS: userAlias,
      ...(app.webAppPort ? { PORT: String(app.webAppPort) } : {}),
    },
    out_file: join(logsDir, `${processName}-out.log`),
    error_file: join(logsDir, `${processName}-error.log`),
    log_date_format: "YYYY-MM-DD HH:mm:ss",
    merge_logs: true,
    autorestart: false,
    max_restarts: 0,
    min_uptime: "5s",
  };
}

/**
 * Add a user app to the ecosystem config.
 */
export async function addUserAppToEcosystem(
  config: UserAppConfig,
): Promise<{ ecosystemPath: string; processName: string; logsDir: string }> {
  const ecosystemPath = getEcosystemPath(config.userRootDir, config.isAdmin);
  const logsDir = getLogsDirectory(config.userRootDir, config.isAdmin);

  // Ensure logs directory exists
  await mkdir(logsDir, { recursive: true });

  // Read existing config
  const ecosystemConfig = await readEcosystemConfig(ecosystemPath);

  // Create app config
  const appConfig = createUserAppEcosystemConfig(config);

  // Check if app with same name already exists
  const existingIndex = ecosystemConfig.apps.findIndex((a) => a.name === appConfig.name);
  if (existingIndex >= 0) {
    // Update existing entry
    ecosystemConfig.apps[existingIndex] = appConfig;
  } else {
    // Add new entry
    ecosystemConfig.apps.push(appConfig);
  }

  // Write updated config
  await writeEcosystemConfig(ecosystemPath, ecosystemConfig);

  return {
    ecosystemPath,
    processName: appConfig.name,
    logsDir,
  };
}

/**
 * Find a user app in the ecosystem config by APP_ID.
 */
export async function findUserAppInEcosystem(
  userRootDir: string,
  isAdmin: boolean,
  appId: string,
): Promise<EcosystemApp | null> {
  const ecosystemPath = getEcosystemPath(userRootDir, isAdmin);

  try {
    const config = await readEcosystemConfig(ecosystemPath);
    return config.apps.find((app) => app.env.APP_ID === appId) ?? null;
  } catch {
    return null;
  }
}
